import GoogleAuth from "@/components/Auth/GoogleAuth";
import Head from "next/head";
import { getSession } from "next-auth/react";

export default function Home({ session }) {
  console.log(session)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Start</div>
        <GoogleAuth />
      </main>
    </>
  );
}

export async function getServerSideProps(content) {
  const session = await getSession(content);
  if (!session) {
    return {
      props: {},
      // redirect: {
      //   destination: "/",
      // },
    };
  }
  return {
    props: { session },
  };
}
